### ISSUE TITLE
[New base] [General] Upscale packs do not scale properly

### ISSUE THREAD

**Issue by sinisterseed** [coelckers/Raze#100]
This causes them to appear enormous apparently, as an user recently discovered with the Blood upscale packs: https://www.doomworld.com/forum/topic/111839-source-port-introducing-raze-thats-one-duked-up-space-marine/?do=findComment&comment=2195884

https://static.doomworld.com/monthly_2020_09/1629204739_04-OZdCorr.png.1587726cf51a1d7fb4bd96d6b9956661.png
https://static.doomworld.com/monthly_2020_09/436950847_05-OZd.png.7f199abcdd6cebbbf54c68ad1bd41cb0.png

It's also causing some weird corruption, as seen on the boat in Cryptic Passage.

**Comment by Phredreeke** [comment]
Looks like it's only the HUD weapon sprites that appears the wrong scale.

The CP texture corruption is not a Raze issue. It's an issue with the upscale pack (it has a workaround for BloodGDX, the standard sprites only upscale pack has a separate file for CP that doesn't load the beast tiles which cause the issue)

BTW, how would one go about loading Cryotic Passage from the command line in Raze?

**Comment by mjr4077au** [comment]
I'll look into how it's doing the scaling but it's probably something best left for Graf.

Regarding loading Cryptic Passage from the command line, you should be able to zip it up and load it like any other zip. Ways you can load CP are:

* ZIP file.
* Raw files straight in your Blood folder.
* Inside a "Cryptic" subfolder of your Blood folder.
* From Blood Fresh Supply via Steam or GOG.

**Comment by coelckers** [comment]
The last alternative would be with -file from any folder. But considering how fragile these Blood mods generally are, the Zip file method comes strongly recommended because it guarantees that the game won't inappropriately pick up its content.

Regarding the scaling, I think it comes from how the texture replacement is done. There's no point trying to fix it as the entire replacement logic needs to be moved to another level in the texture management to be transparent.

**Comment by Phredreeke** [comment]
I place the upscale mod in a zip file, but I can't rely on the user having Cryptic Passage in any specific configuration.

Now it was some time since I tested, but I recall I loaded cryptic.ini from the command line and it would display the plasma pack tiles instead.

**Comment by coelckers** [comment]
I'll have to test what it does with these tiles. I have generally used CRCs every time I had to replace something to make sure it won't override different content, like Cryptic Passage or user mods. I can understand why for such replacement mods it may be a bit much work but it surely improves stability of the whole thing.

**Comment by Phredreeke** [comment]
Thank you for recognising what a massive hassle adding CRCs for each upscaled tile would be.

The problem is that Cryptic Passage uses the same range of tile numbers as used by the beast. For GDX I resolved it in the ugly way of duplicating the overlapping tile numbers with their CP equivalents. Given that GDX didn't support palette emulation at the time I found that adequate. I still don't know any better way to do it. For NBlood I made a separate BAT file that used a different DEF file which excluded those tiles.

**Comment by coelckers** [comment]
I added a hotfix for the weapon. I won't be able to do a proper backend fix today, that takes a bit more time.

**Comment by coelckers** [comment]
Except for fonts this should work now. Since fonts do not use the textures of the original tiles they will need a bit of glue code to pick up the hires replacements.

**Comment by duke912** [comment]
> Except for fonts this should work now. Since fonts do not use the textures of the original tiles they will need a bit of glue code to pick up the hires replacements.

Just downloaded latest dev build (alpha-286) and tested upscaled pack on both Shadow Warrior and Duke 3D, all sprites works fine, except the HUD weapons which loads incorrect.

**Comment by coelckers** [comment]
If you want to load the hires packs you have to use the -nowidescreen option, because in many cases the widescreen sprites clash with the hires content. The Duke pack only has weapon models which are not supported yet so if you use that the weapons will still be lo-res for now.

**Comment by coelckers** [comment]
I think this can be closed now. If there's specific problems please open new reports for each.
