### ISSUE TITLE
[General] autoexec.cfg is not being activated

### ISSUE THREAD

**Issue by Mechanical-sanity** [coelckers/Raze#110]
autoexec.cfg not working. The commands within it work, so that's not the issue.

**Comment by mjr4077au** [comment]
As discussed on Discord a few days ago, it appears the code for this (`FGameConfigFile::AddAutoexec()`) is there, but is not called from anywhere. I need to determine whether it's just a missing call or whether it's incomplete and that's why it's been left out.

@coelckers do you recall by chance where this got up to back in the early days?

**Comment by mjr4077au** [comment]
This is partially resolved. @Mechanical-sanity for your discussed usage of just wanting `vid_fps 1` set, can you please place an autoexec.cfg file into Raze's running directory and test? That should work for you.

When I have more time, I'll look into what needs to happen for autoexec.cfg files coming in from search directories like Duke or Duke.Duke and content directories like Steam, etc.

**Comment by mjr4077au** [comment]
I'm not sure on this having thought about it further. Autoexec.cfg from the running directory is now working as expected following a9ad043c36f3c77f7a876edfd4450e7d6c938052. If additional files need loading, there's always the `-exec` command line argument for this.
