### ISSUE TITLE
[53481fb9a] [Blood]: First secret in E1M1 broken.

### ISSUE THREAD

**Issue by mjr4077au** [coelckers/Raze#127]
Changes in 53481fb9a300aa7ac56330a2fd8379db5f6dbb8c have caused the below secret to become inaccessible. Credit to markanini on Discord for the report.

![Blood_0001](https://user-images.githubusercontent.com/48643140/95970749-0a72ae00-0e5c-11eb-8c8a-c26dc300d850.png)

**Comment by coelckers** [comment]
Don't you just love it when some refactoring reveals a bug in the underlying game?
Turns out that the first element (index 0) of these X arrays cannot be used because there's some code out there that writes in there through uninitialized data...
I had no choice but to skip that element because finding and fixing all code that may do this is not feasible,

**Comment by sinisterseed** [comment]
Gotta love these games in general, was just about to mention this but mark beat me at my own game 😉 .

But why uninitialized data out of all things?

**Comment by coelckers** [comment]
The entire thing is typical Blood. They wanted to save a few kilobytes of memory so they only provide a small number of these X structures and reference them through the 'index' field in the map data, and then added a ridiculously complex management scheme, which has a few flaws and design odditiies. What I did here was remove that management because it was totally pointless.

This index field is supposed to be -1 when not used, but for freshly cleared data it is 0, not -1, and some code is apparently acting on such uninitialized entries in the data, killing the first entry in the process. Not during actual game play but only on map load, but that's bad enough here.

The old allocator, complete with linked free list starts at the back of the array, so entry 0 would only be used if the allocator totally ran out of free slots.
