### ISSUE TITLE
SW - 0.7.1_alpha-313 - Player speech option does not work

### ISSUE THREAD

**Issue by Axldomi** [coelckers/Raze#144]
1.) In Shadow Warrior, Lo Wang keeps talking although "Player Speech" is turned "off". The option works as intended in Duke3D.

2.) It also seems that turning the speech "on" or "off" in one game automatically changes in the option in the other game. For example when I turn it off in Duke3D, the option will also be turned off in Shadow Warrior (although like mentioned in 1, does nothing in SW).

**Comment by sinisterseed** [comment]
It carries over into the other games I think. I think it's safe to assume this one as a bug though.

As for the setting having no effect in SW, this is known since forever but it isn't something easily solved. To make that feature actually work, listening to each and every quote and marking it for effect is an incredibly time-consuming and tedious process, which is why it has not been done so far, and won't be for some time due to how much time that actually involves.

There's simply more important work to do instead.

**Comment by sinisterseed** [comment]
I've actually figured I'd spend some of my free time fiddling with this stuff, and made a PR for it.

But please keep in mind that, as I've explained there, such a feature can never be perfect in this game. Sensible choices can be made, like I just did, but more than that, I doubt can be done. SW was clearly designed with character and player speech in mind.

**Comment by Axldomi** [comment]
Thanks for the feedback. For me personally, this feature isn't necessary, since - like you've said - these games are made for player speech. And moreover, there are for more important issues at hand.

I just pointed it out by testing the latest builds. If you and the other developers choose to disable this feaure, fine by me.

**Comment by sinisterseed** [comment]
No problem, feedback is always appreciated 😉 .

The thing is, Blood, Exhumed, and Duke work better with such a feature thanks to their design where the player does not interact with other NPCs, but SW has quite a few of those, and in Blood, the sole exception is the hanging Duke secret if I recall correctly.

**Comment by coelckers** [comment]
now it works.
