### ISSUE TITLE
Cannot start any game

### ISSUE THREAD

**Issue by Talon1024** [coelckers/Raze#164]
If I try to run Raze with any supported game, I get this error on startup:

    raze.pk3:zscript/razebase.zs, line 63: Unknown native class BloodStatusBar
    raze.pk3:zscript/razebase.zs, line 66: Unknown native class DukeCommonStatusBar
    raze.pk3:zscript/razebase.zs, line 69: Unknown native class DukeStatusBar
    raze.pk3:zscript/razebase.zs, line 72: Unknown native class RedneckStatusBar
    raze.pk3:zscript/razebase.zs, line 75: Unknown native class ExhumedStatusBar
    raze.pk3:zscript/razebase.zs, line 78: Unknown native class SWStatusBar

**Comment by mjr4077au** [comment]
Are you using a devbuild or your own compile? If you've built locally, I'd delete raze.pk3 and build again, it shouldn't recompile but rather just generate a new pk3 file.

**Comment by Talon1024** [comment]
I'm using my own build based on the latest Raze revision. None of my local files are modified.

**Comment by mjr4077au** [comment]
Was it a 100% clean build from scratch or an rebuild? If rebuilding, try deleting the raze.pk3 file so MSVC can regenerate it from scratch. I've seen this before from time to time.

**Comment by Talon1024** [comment]
It's a 100% clean build, so I don't think deleting raze.pk3 will help. I'm on Linux (Kubuntu 18.04).

**Comment by mjr4077au** [comment]
Ah righto, no worries then 😄.

When my PC shit the bed the other day, I reset the CMOS and lost the boot stub for my Linux partition. I'll try to get it going and test whether I can run the game after a clean build also.

**Comment by coelckers** [comment]
This error means that it doesn't find some needed content from raze.pk3, so it must pick up some old version from somewhere.
Best check the path in the console log and verify that the file contains everything.

**Comment by alexey-lysiuk** [comment]
It's caused by class registration via custom sections. Symbols from static libraries, status bar classes in this case, are placed after [the corresponding tail pointer](https://github.com/coelckers/Raze/blob/aed8a450fd7e6a8e5fcecbc4f2bb5b5284322b89/source/zzautozend.cpp#L61).
At the moment, I have no idea how to fix this. Apparently, POSIX targets are affected by this problem.

**Comment by coelckers** [comment]
The big problem here is that if I put all the game source files into the main project, compilation with MSVC becomes excruciatingly slow because apparently some internal table overflows after a certain amount of source files and precompiled headers do not get used anymore. That was the only reason I added the subprojects.

**Comment by alexey-lysiuk** [comment]
I’m fine with subprojects. The problem is that custom sections thing. It caused similar issues before, it does the same again. I’m for replacing it with anything that is based on C++ standard.

**Comment by coelckers** [comment]
That'd mean replacing a lot of stuff because it's not just the class definitions but also the variable exports and the action function exports and changing this will add a lot of boilerplate code that not only inflates the executable but also will delay startup a bit - not much but this may end up in thousands of function calls. For now I'd do the same thing I did with the menu exports - move just the affected files to the main project.

Or is there a way to import sources from a separate CMakeLists.txt file into the main project so that we can work around the issue for the time being?

**Comment by alexey-lysiuk** [comment]
If standard-bases solution considered unacceptable due to its implementation details, I would keep custom sections, and would eliminate dependency on linking order instead.
This will add a bit of complexity because getting executable section's content is platform specific by definition.

**Comment by alexey-lysiuk** [comment]
I propose to fix it like in #171. Of course, this should be implemented for other platform. Still, I made this PR to present the idea.
