### ISSUE TITLE
Duke3D - 0.7.3_alpha-316- Weapon Prev / Next with alternative weapons (Expander / Incinerator)

### ISSUE THREAD

**Issue by Axldomi** [coelckers/Raze#182]
I'm not quite sure if this intended or not, but the current system seems a bit weird for me. I'll explain:

The Expander / Incinerator are currently chosen by pressing the "alternative weapon" key. --> OK.

However, when the alternative weapon is chosen, the "previous weapon" key does not work in both cases (can be very dangerous in tight battle). --> Not OK.

Moreover, when the expander is equiped, the "next weapon" key will make you select the pistol (instead of the devastator).  --> Not OK.

If the incinerator is equiped, the "next weapon" key, will give you the pistol (which makes sense, since it is the alternative for the freezer which is the last weapon).  --> OK.

My apologies, if this is truly intended behaviour, but I feel this could be improved.

**Comment by duke912** [comment]
I played a bit of Duke after I saw this thread, and I think it's even better if the devs add an option to be able to select all weapons through next/previous weapon key binds, playing with a controller there isn't much buttons left for hotkeys/alt weapon to bind after you set up all the buttons.

**Comment by mjr4077au** [comment]
> However, when the alternative weapon is chosen, the "previous weapon" key does not work in both cases (can be very dangerous in tight battle). --> Not OK.

This is because the extra/alternate weapons are not in an expected order since they were added after the fact. Below is how they're ordered, with the first entry being 0:

```
enum dukeweapon_t
{
	KNEE_WEAPON,  // 0
	PISTOL_WEAPON,
	SHOTGUN_WEAPON,
	CHAINGUN_WEAPON,
	RPG_WEAPON,
	HANDBOMB_WEAPON,  // 5
	SHRINKER_WEAPON,
	DEVISTATOR_WEAPON,
	TRIPBOMB_WEAPON,
	FREEZE_WEAPON,
	HANDREMOTE_WEAPON,  // 10
	GROW_WEAPON,
	FLAMETHROWER_WEAPON,    // World Tour

	MIN_WEAPON = 0,
	MAX_WEAPON = 9
};
```

Because GROW_WEAPON (Expander) is last on the list, the next weapon when looping around is of course the pistol.

I'm not saying any of this is unchangable, but just explaining the logic behind it.

I have a bit of leave this afternoon from work so I might try something around your suggestions in a separate branch. That way, it can be tested and receive team approval prior to merging.

**Comment by coelckers** [comment]
You cannot just cycle through this list. Proper cycle order should be determined by weapon slots.
In RR this is even more extreme because there's additional weapons in these slots - and index 10 is not a 'proper' weapon in both.

**Comment by mjr4077au** [comment]
Yeah, I know. I was just trying to illustrate to the OP why the Expander goes to the pistol as the next weapon.

**Comment by coelckers** [comment]
Note: This one needs fixing before doing a new release.

**Comment by coelckers** [comment]
It was only the Raze-exclusive 'alternative weapon' switch that was broken because it didn't set the 'subweapon' variable.
I'm still at a loss how anyone can write such obtuse code to cycle through a handful of weapons that makes even supposedly trivial feature extensions break apart at the tiniest mistake.

**Comment by mjr4077au** [comment]
Thanks for taking a look and fixing it up. Clearly my mistake since I did the initial uplift in 51a08fbaf34e86f9eb8ab69f4fc836ecf9c91b98, just didn't reference the other code blocks where it was set.
