### ISSUE TITLE
Duke3D - 0.7.3_alpha-318- E1M4 - Under Water Toxic Waste - Screen colour

### ISSUE THREAD

**Issue by Axldomi** [coelckers/Raze#186]
See screenshots below. As soon as I swim under the toxic waste spot, the screen will change colour. This does not happen in EDuke32.

I also provided a savegame.
[save0000.zip](https://github.com/coelckers/Raze/files/5575126/save0000.zip)

![Duke_0000](https://user-images.githubusercontent.com/71838912/99830038-69170000-2b5d-11eb-949e-032c45920655.png)

![Duke_0001](https://user-images.githubusercontent.com/71838912/99830046-6caa8700-2b5d-11eb-8729-d27dfda8c4a1.png)

**Comment by coelckers** [comment]
Figures that they managed to abuse this engine bug in the game.
It's actually quite simple what happens here: Duke stores the current palette in the player and never updates this when transitioning between two underwater sectors with different palette effects. Raze works quite differently here and only queries the palette when rendering the scene. Obviously that picks the 'correct' one. 
So the interesting thing will be to check what happens if you dive in the toxic spot and swim elsewhere...

**Comment by sinisterseed** [comment]
> So the interesting thing will be to check what happens if you dive in the toxic spot and swim elsewhere...

Funny you mention it, because I just investigated what happens in GDX 😉 .

And it's what you would expect. If you jump into the spot but move outside of it, the palette doesn't change and remains green. Likewise, going underneath that spot doesn't change the palette if you're coming from the blue water zone.

**Comment by coelckers** [comment]
Thanks for confirming. I really do not fell like un-fixing this thing. The original palette code was quite the total mess.

**Comment by sinisterseed** [comment]
I agree.

**Comment by dibollinger** [comment]
The original behavior is intentional, to show that the player is submerged in slime instead of water.

The way it works now in Raze (as of 1.1.0pre-543-ga2f17b1de) is that the green tint will disappear whenever the player is not under a slime ceiling. This can be observed in E2L6 (Tiberius Station) and is definitely not intended by the map author.

Test map:  [slimecolor.zip](https://github.com/coelckers/Raze/files/7076597/slimecolor.zip)

**Comment by NY00123** [comment]
Another example is the pool of slime in E1L6, with the octabrains above it. After progressing further into the game, a path to a secret area opens from this pool's "underwater" sector. The green-tinted palette (slime / night-vision) is used while staying below slime tiles, and it changes to the bluer underwater palette in 1.2pre-547-g1228cb604 within the connecting path.

The slime palette is the one exclusively in use in DOS version 1.5, albeit there are a couple of issues even in this version:
- The last set palette isn't properly restored when loading a saved game. So when doing so in an underwater sector while not staying below a slime tile, the usual underwater palette will be unconditionally used.
- The same can be done by turning night vision goggles on and off.
