### ISSUE TITLE
Duke3D - 0.7.3_alpha-439 - General - Weird ambient noises at various places

### ISSUE THREAD

**Issue by Axldomi** [coelckers/Raze#196]
I'm noticing some weird ambient noises at various places in Duke. I provided a savegame of such place (rooftop Flood Zone).

[save0001.zip](https://github.com/coelckers/Raze/files/5591313/save0001.zip)

**Comment by sinisterseed** [comment]
This is consistent with GDX, just warped to investigate there.

Doesn't seem a bug to me.

**Comment by Axldomi** [comment]
Very strange. Walking around at the rooftop, I hear noise that I don't notice in Rednukem or EDuke32...

**Comment by sinisterseed** [comment]
Hm, fair enough. Let me double-check at full volume, maybe my ears are deceiving me, it's happened before.

**Comment by coelckers** [comment]
Remember: 'stat sounddebug' is your friend. What does it say?

**Comment by sinisterseed** [comment]
Alright, there is in fact a difference, but it doesn't seem to be quite where Axl said.

If I go near the yellow door I can hear that machine noise in GDX too, with the sole difference that it's quieter and I have to get closer to the mountain to the left.

However, staying here does seem to make some sounds I don't hear in GDX show up for us. According to sound debug, they're these:

![Duke_0007](https://user-images.githubusercontent.com/57503728/100137525-448c9200-2e95-11eb-8f8d-f809d55f7c0a.png)

In GDX I only hear the water dips when standing on that side of the building. Which also seem to be missing for us.

**Comment by sinisterseed** [comment]
Alright, I gave this a couple more spins today, since this had been staying on my mind and I had the feeling that something eluded me last night when I was tired and with a slight headache - yay, glorious tinnitus... But now I'm fresh and I hear everything.

So, I have made some mistakes. That mechanical noise plays pretty much **_everywhere_** on the roof **_where the water dips are also heard_** (see screenshot above). The water dips are actually NOT missing or inaudible BUT, it's easy to miss them because they are heard **_only at the end of that mechanical noise_**, which explains why I didn't hear them at all last night.

Now regarding the yellow door, spatialization also seems a bit odd for us vs GDX. As I mentioned, the water is quite loud for us even when sitting right in front of the door, as if the water is right in front of me, and I can hear it to my left as well. 

This is in contrast with GDX, where if I stand right in front of the door, I only hear the water when I go to the left and approach that small cave, I appear to hear nothing right in front of me otherwise.

**Comment by Axldomi** [comment]
First of all, many thanks Sinisterseed for looking in to the issue (I was already thinking I was going nuts here :-) ).

On the subject, yes, it's like this weird constant mechanical noise. There are other places as well where I notice this (for example when you first enter the large central room in E1M6 Launch Facility where you need to follow up the ramp to reach the locked-combination door that holds the blue key).

**Comment by coelckers** [comment]
Something on that roof sets a bogus reverb and that amplifies the water sound to this monstrous noise.

**Comment by sinisterseed** [comment]
> Something on that roof sets a bogus reverb and that amplifies the water sound to this monstrous noise.

Ah, so that's what it is.

> On the subject, yes, it's like this weird constant mechanical noise. There are other places as well where I notice this (for example when you first enter the large central room in E1M6 Launch Facility where you need to follow up the ramp to reach the locked-combination door that holds the blue key).

Know the feeling for sure, it's especially confusing when the differences are more subtle, or the problems are.

I'll go check that map out as well, if you know more bizarre locations please do tell, so we can investigate them too and fix everything ❤️ .

**Comment by coelckers** [comment]
Unfortunately there's no easy fix. These reverb activators are distance based, not sector based and this one just happens to cover a few parts of the level it's not supposed to

**Comment by sinisterseed** [comment]
Well, that sucks.

Now for E1L6, based on Axl's description I think it's this area with the toxic slime:

![Duke_0000](https://user-images.githubusercontent.com/57503728/100241627-90464680-2f3c-11eb-81e5-27e7a9970382.png)

In this case, however, I think there's no real bug here. I think. The difference versus GDX here is that we seem to just make the other sound louder, the one with the chatter, which I hear in GDX too, but it's drowned in the bubble noises there instead.

**Comment by Axldomi** [comment]
Below are screenshots of the exact spots where I notice this "noise":

E1M6: Launch Facility. Right onder the first bridge. 

![E1M6](https://user-images.githubusercontent.com/71838912/100244940-c92fec80-2f37-11eb-93b3-f87b003665c9.png)

E3M4: Flood Zone. Rooftop near the yellow door.

![E3M4](https://user-images.githubusercontent.com/71838912/100245107-faa8b800-2f37-11eb-8675-473ab04dd6bb.png)

E4M1: It's Impossible. At the start of the level, in the secret cave.

![E4M1](https://user-images.githubusercontent.com/71838912/100245205-12803c00-2f38-11eb-9a9a-1fd8e1dea44e.png)

**Comment by sinisterseed** [comment]
Thanks ❤️ .

I investigated the cave on E4L1 too, and this is what the output says:

![Duke_0001](https://user-images.githubusercontent.com/57503728/100251520-89710100-2f47-11eb-9862-236de9727a02.png)

Similar to E3L3, this cave does sound very different for us than in GDX. Currently it sounds as if there's an engine there and the player is inside a facility, which is in stark contrast to GDX, where all that is heard is the fire burning, storm and lightning outside, and guess what, water dips!

I wouldn't be surprised if this turns out to be related to whatever is wrong on E3L3. But for E1L6, I don't know what to say. To me it sounds the same as GDX.

**Comment by coelckers** [comment]
It's the reverb for sure. The main problem here is that the reverb of the original Duke sound engine was not true reverb but some bad sounding cheap hack. The ZDoom reverb environment that sounds good for sewer tunnels is entirely unsuitable for everything else because it amplifies background effects too strongly. I think we have to switch to a weaker preset for most areas.

**Comment by sinisterseed** [comment]
Alright then.

Any suggestions? If I recall correctly, the one we're currently using was the weakest of all - which still needed further adjustment, because it was too loud.

**Comment by coelckers** [comment]
The only way to deal with this is use a weaker reverb. That obviously sucks for sewers but what can you do if the game has such pathetic definition methods?

**Comment by coelckers** [comment]
Maybe it can be done with a flooding algorithm similar to what GZDoom uses for dynamic lights so that the reverb does not bleed into unrelated parts of the map, but that requires quite a bit of refactoring because it needs to supplement the sprite based reverb checks with sector based ones.
