### ISSUE TITLE
Where to put all game files?

### ISSUE THREAD

**Issue by xcom169** [coelckers/Raze#201]
Hello!
Where to put all game files?
To the same dir as the .exe ?

**Comment by sinisterseed** [comment]
That depends on the origin of the games.

If you own them on Steam or GOG, their installation is detected via a registry scan and no further action is required.

Otherwise, yes, you will have to create a folder inside Raze's root directory for each game - it's a bad idea to toss them all into a single folder, don't do that. Inside them, for Duke and SW you'll need just the GRPs, for Powerslave/Exhumed the STUFF.DAT, DEMO.VCR, and BOOK.MOV files, and for Blood these:

BLOOD.INI
BLOOD.RFF
GUI.RFF
SOUNDS.RFF
SURFACE.DAT
TILES000.ART-TILES017.ART
VOXEL.DAT

Shadow Warrior and Powerslave use CD music. You will have to place it in the same directory with the respective games. They need to be titled trackXX, in ogg format. Powerslave is from track02 to track19 for instance.

If Raze doesn't pick up the music automatically, after running it once it will generate an INI file, which is its configuration. Edit one (or more) "Path=" parameters and add the path to the music of each respective game.

**Comment by coelckers** [comment]
Small correction: For Powerslave/Exhumed you do not need DEMO.VCR.

The default configuration for the search path looks in the program directory and in direct subdirectories of the program directory for game data. So unless you got Steam/GOG installations that are autodetected there's 2 options:

1. Copy all games to a properly named directory in the folder with raze.exe
2. If you do not want that and rather let Raze pick up your existing installations, open 'raze-{username}.ini and manually add the paths to your games to the [GameSearch.Directories] section - the format must be 'Path={full path to game} for each. You can use '*' as a wildcard, e.g. if all your games are in subdirectories of "C:\My Games\" you can just add "Path=C:\My Games\*" to let them all be found at once.

**Comment by coelckers** [comment]
An important advice is also to not put data from different games into the same folder - this may cause interference, especially with games like Blood that do not group everything in a single container file.

**Comment by krazov** [comment]
I manage to get this. I died in the fire, and along with the hands' animation, and a corpse of Anubis Zombie appeared. After reloading the next day, I can see the insect:

![Exhumed_0002](https://user-images.githubusercontent.com/9447478/120902592-7ac77d00-c641-11eb-91a5-d0c8063f082f.png)

I noticed that if I zoom, it moves to the center:

![Exhumed_0003](https://user-images.githubusercontent.com/9447478/120902593-7b601380-c641-11eb-98f4-20d54936d231.png)

It disappears completely when in minimalistic HUD, and I tried to play like that, however, the health number doesn’t update which is even more serious than the sprite offset (so I’m playing with the insect on).

![Exhumed_0004](https://user-images.githubusercontent.com/9447478/120902594-7bf8aa00-c641-11eb-88cd-230b78334a89.png)

**Comment by sinisterseed** [comment]
> I manage to get this. I died in the fire, and along with the hands' animation, and a corpse of Anubis Zombie appeared. After reloading the next day, I can see the insect:
> 
> ![Exhumed_0002](https://user-images.githubusercontent.com/9447478/120902592-7ac77d00-c641-11eb-91a5-d0c8063f082f.png)
> 
> I noticed that if I zoom, it moves to the center:
> 
> ![Exhumed_0003](https://user-images.githubusercontent.com/9447478/120902593-7b601380-c641-11eb-98f4-20d54936d231.png)
> 
> It disappears completely when in minimalistic HUD, and I tried to play like that, however, the health number doesn’t update which is even more serious than the sprite offset (so I’m playing with the insect on).
> 
> ![Exhumed_0004](https://user-images.githubusercontent.com/9447478/120902594-7bf8aa00-c641-11eb-88cd-230b78334a89.png)

Same as #415.

Please don't report issues in closed or unrelated topics, that ensures they only get missed.
