### ISSUE TITLE
[8a7b3dc] [Blood] Jittery platform

### ISSUE THREAD

**Issue by sinisterseed** [coelckers/Raze#205]
While investigating the save issues, I noticed this rotating secret wall right here jitters when it's moving the player.

![Blood_0000](https://user-images.githubusercontent.com/57503728/100552567-bcd9c580-3290-11eb-9b6f-eff96ce3feb5.png)

[jitter.zip](https://github.com/coelckers/Raze/files/5612801/jitter.zip)

**Comment by coelckers** [comment]
What I find far more interesting is that this thing counts as a secret every time it is triggered.
The effect here is clear, though. The wall movement is interpolated but the player's angle is out of sync with it. And the code is in very different places - the sector action only interpolates the player's world angle for rendering as a sprite but not the view angle.

@mjr4077au Do you have an idea?

**Comment by mjr4077au** [comment]
I'll have to have a look after hours as I just clocked on for the day.

What happens when cl_syncinput 1 is used?

**Comment by coelckers** [comment]
With cl_syncinput 1 it's all ok.

**Comment by sinisterseed** [comment]
Funny you mentioned the secret, I thought I saw something strange when I took this but I was too tired to realize what it was.

That explains how I jumped from 5 to 9 secrets without finding any more of them, lol.

**Comment by mjr4077au** [comment]
> With cl_syncinput 1 it's all ok.

Thanks for confirming, at least that'll give me something to work with when I get home 😄.

**Comment by mjr4077au** [comment]
So what's happening here is is that the player can't be on an interpolated sector object while not interpolated themselves.

The same thing can be observed in SW for vehicles except the turret in $dozer. For this, I put in some checks to not interpolate SO_TURRET. When I'm on an actual PC, if I can find where to skip interpolating this secret if `cl_syncinput 0`, that will fix the issue.

As a side comment, I had a really hard time uninterpolating the other vehicles in SW and ended up putting in some fudge code to force `cl_syncinput 1` when on a boat or a tank. It'd be ideal to unroll all of that shit and not interpolate those vehicles while `cl_syncinput 0` like the turret.

**Comment by sinisterseed** [comment]
If you know a better way of doing it, then that's all the better IMO.

As a small note, I will take a break from things today, most likely. I woke up with an infection on one of my fingers this morning 😥. It seemed like nothing at first, but good grief no, it sure was an infection. Cleaned that mess and it's better now, but still in no position to test anything.

**Comment by mjr4077au** [comment]
It's more just trawling Blood's code to find what's what because it's harder to navigate than SW (for me in any case). I'm hoping it's resolvable. When I broke some of the interpolation stuff up as testing, it seems like the wall is made of three sprites so could be a shit fight. The issue also happens in NBlood.

I'm sorry to hear about the finger... I'm notorious for biting my nails when stressed which usually is what starts this stuff off. I need to try and cut that shit out.

**Comment by sinisterseed** [comment]
It's made of three sprites? Oh boy, yeah, this will probably turn into a shit fight...

We got that in common then, I'm notorious from biting my nails off as well, especially under stress or pressure. This time however, I did nothing. I think something just grew up quite badly there, by the looks of it, which led to an eventual, sudden infection.

I literally just woke up with it inflamed, and harder than usual this morning. Then I cut a small corner just to see what's there, and pus started flowing...

**Comment by coelckers** [comment]
Since it works with synchronized input - is there any way to temporarily revert to it for this case?

**Comment by mjr4077au** [comment]
Yes, I just need to find out how the door works. I didn't get home until safer 9pm from work so I wasn't able to have a further look.

Once I work that out, I can just synchronise the input there but I consider that last resort. Will try to work it out properly first.

I've been talking about not interpolating the sector object when the player input is unsynchronised like I did for SWs turret, but that might not be the issue here. If you look at the revolving door on the automap while it's turning, it actually appears uninterpolated so maybe that's the key in this case.

FWIW, we're not alone in this case as it also happens in NBlood when I cross checked it.

**Comment by coelckers** [comment]
The door gets interpolated, that I was able to confirm.

**Comment by mjr4077au** [comment]
Was that where `viewInterpolateWall()` is called?

**Comment by mjr4077au** [comment]
This is fixed in the same manner that the tank/boat in SW are fixed. It should be revisited at some point but I've gone for the quick win of just forcing synchronised input for now.
