### ISSUE TITLE
[Alpha-523][SHADOW WARRIOR] Glitched vehicles/mounted weapons

### ISSUE THREAD

**Issue by duke912** [coelckers/Raze#211]
When firing with a mounted turret or vehicle, the 'firing position' which is in front of the turret/vehicle, doesn't follow you when you turn around, and you can even shoot yourself (and crash the game when you die).

[save0001.zip](https://github.com/coelckers/Raze/files/5638318/save0001.zip)

save is in the second level, you can test on both the mounted turret and the forklift. You can also notice how the 'Titsubish' glitches when you turn the forklift.

**Comment by sinisterseed** [comment]
Goodness, these things just love breaking... we fix them but nah, they insist.

The projectile doesn't spawn correctly either as far as I see:

![ShadowWarrior_0000](https://user-images.githubusercontent.com/57503728/101076088-8e6b2b80-35ab-11eb-9068-4096182f9c27.png)

**Comment by mjr4077au** [comment]
Thanks mate, will also take a look at this and get it right (again).

**Comment by sinisterseed** [comment]
Indeed, since they just laugh at us 😆 .

It's quite bad this time around. This prompted me to check Darkwoods again, particularly its turret section, but it currently runs at the risk of softlocking. The tank's turret actually doesn't do a full rotation anymore, I can't even aim at the door before the portal, the shots are fired behind me lol.

I wonder if the two pillar-platforms are also broken, but I can't get to that point currently.

![ShadowWarrior_0000](https://user-images.githubusercontent.com/57503728/101079515-44387900-35b0-11eb-8d43-471e4acf7b6b.png)

[brokentanks.zip](https://github.com/coelckers/Raze/files/5638561/brokentanks.zip)

**Comment by mjr4077au** [comment]
Broken from 06a069750f83f5e701a525bc56301e5d7cd36658.  I'd hypothesise the changes in track.cpp are responsible for this.

Will take a further look on the way home unless someone else wants to step in, wanted to look at Exhumed before I get to work in ~20 minutes.

**Comment by coelckers** [comment]
Well, it's late here, so certainly not for the next 18 hours.

**Comment by mjr4077au** [comment]
I'll look in ~8-9 hours then 😄. Have a good evening!

**Comment by sinisterseed** [comment]
And you have a good day, MJ 😁.

**Comment by mjr4077au** [comment]
It's Friday, can't be bad! 😁

**Comment by coelckers** [comment]
So, time for a new release?

**Comment by mjr4077au** [comment]
Sounds good to me 😁.

**Comment by sinisterseed** [comment]
Aye, captain ☺️.
