### ISSUE TITLE
Duke3D - Raze 0.8.0. - Sky in E4M1 too fast.

### ISSUE THREAD

**Issue by Axldomi** [coelckers/Raze#217]
Found a first bug in the new beta release. The sky in the very first level of episode 4 (It's Impossible) is moving too fast.

![Duke_0000](https://user-images.githubusercontent.com/71838912/101279806-06f90480-37c5-11eb-9a43-72e79fb0ccfc.png)

**Comment by mjr4077au** [comment]
Ah shit, that didn't take long 😅.

I dare say a fix similar to 977223287e10e371296bbb7b4c5ecec751a0ab24 is needed for this.

**Comment by sinisterseed** [comment]
Heh, yeah, it didn't cross my mind to recheck the animated skies following the recent improvements either, oops.

**Comment by coelckers** [comment]
It's not a frame rate problem. Just an oversight with texture offsets due to merging the sky tiles into one texture.

**Comment by mjr4077au** [comment]
Ah right, that actually might make sense.

I tracked this down to d545eb7aa98827935f877d6d2e572dda6090906a but even with this repair its a bit too fast. Might need a two-pronged approach, I guess.

**Comment by coelckers** [comment]
It's better now. 
The remaining speed issue was, as expected, the composite texture's effect because it threw the panning effect off the rails - panning in Build is in texture units, not map units.
I also made a few variables floating point because the effect looked awful at certain angles where it lost all precision.
