### ISSUE TITLE
[Duke] problem with vertical movement when falling

### ISSUE THREAD

**Issue by shaggi72** [coelckers/Raze#220]
when jumping from a high place, duke bounces when falling, during the second that bounces the vertical movement of the mouse does not work

to reproduce it you just have to start the first mission of the game, you just have to move the mouse up and down while it is thrown through the ventilation duct

the problem is from version 0.7, I can't reproduce it with EDuke32 (I was able to reproduce it in the latest version of EDuke32, but it lasts half the time, or even less)

I hope it is understood, I do not speak English and I use a translator

**Comment by sinisterseed** [comment]
I think you refer to when Duke looks down into the ground when he lands, when the player cannot do much before that small sequence ends.

I am pretty sure this is vanilla behavior, and it's the same in GDX.

**Comment by sinisterseed** [comment]
Actually... perhaps not.

Just rechecked with GDX and something does feel different, insofar as for us it's like it's blocking vertical mouse movement when landing, but I'm gonna need a second opinion here.

@coelckers & @mjr4077au how does this feel to you versus GDX? Our changes nonwithstanding.

**Comment by Axldomi** [comment]
I've been willing to report this myself for some time, but was a bit hesitant as I'm also not quite sure. Duke has the nasty habit to center his view after landing from a higher level (wish there was an option to disable this behaviour).

Anyway: in both EDuke32 and Raze however, this will also block vertical mousemovement for a certain moment after landing. And it appears Rednukem does not have this issue.

**Comment by sinisterseed** [comment]
Yeah, that's the issue.

I kinda feel something is different, our different implementation nonwithstanding, but it's difficult to put my finger on it. It could just as well be placebo, and why more opinions are required. The more, the merrier 👍 .

**Comment by mjr4077au** [comment]
That's original behaviour and is observable in other ports like EDuke32. It's only Duke that does this. EDuke32 does this as well and I presume Rednukem does as well.

**Comment by sinisterseed** [comment]
Agreed. This and the Exhumed turning speed definitely need one.

**Comment by mjr4077au** [comment]
My understanding is that when Graf rebased on JFDuke3D, a number of observations were made on the outgoing EDuke32 code as a reference guideline of a more modernised input system. If it originates from EDuke32, that's why its there.

First place the lock occurs:

https://github.com/coelckers/Raze/blob/92bf1232da4c6eaae7b57b77ed71fa1c5d4b4eac/source/games/duke/src/player.cpp#L1002

When searching the JFDuke3D code for `hard_landing`, I found the below equivilent however its only blocking avel and not horz. I think this will need further review when I have time to ensure we're doing things accurately.

https://github.com/jonof/jfduke3d/blob/5a57ff0fa6f255d8bc5a17513245c534ae9a2ed3/src/game.c#L8735-L8747

Second place the lock occurs.

https://github.com/coelckers/Raze/blob/1a2b93f4029559a796aa1939817a2a20a09ed985/source/games/duke/src/input.cpp#L828-L836

When searching the JFDuke3D code for `return_to_center`, I see nothing that indicates that his port is blocking input while its greater than 0 which probably means we should drop it. Please do note we don't have or use this variable anymore, but the code emulates its functionality.

**Comment by coelckers** [comment]
EDuke32 was never referenced here. I only used RedNukem for that.

**Comment by mjr4077au** [comment]
Fair enough, boss ☺️. I'll take a further look at this tonight in any case to ensure we're accurate with how we're doing things as I think this is a discrepancy from my brief look at it this morning.

**Comment by mjr4077au** [comment]
I'm hoping the enclosed commit fixes this satisfactorily. What we were doing here ultimately wasn't very different from the original source at all. I've removed an input block that cleared horz (vertical) input while returning to center which should address the issue.

@shaggi72 for reference, EDuke32 doubled the return speed some time ago which is why its faster than default. Rednukem is a better representation of original game behaviour.

**Comment by mjr4077au** [comment]
@Axldomi I've reverted the commit that closed this issue in lieu of what I feel is more accurate to the original game as removing the block entirely wasn't right either.

When returning to centre, the original game had a variable called `return_to_center` which would be set to 9, and the game would keep trying to return to centre until it got to zero, or the player's horizon value was 5 units out from centre.

What Rednukem (and the original game) does is allow mouse input even while `return_to_center` isn't 0, meaning the player can fight the algorithm. The game will keep trying to return you to centre, but will give up when `return_to_center` is 0 irrespective of whether you're there or not. This is why it might feel like you're in control, even though Rednukem does still try to return you to centre.

We removed this `return_to_center` variable some time ago as part of clean up and were continually trying to return to centre until we got the player back to centre. This is also what EDuke32 does, but they do still have `return_to_center`.

What I've now done is allow the player to provide mouse input when they're returning to centre and within 5 units from the centre line. This allows faster mouse input when close to the centre mark, but still blocks it most of the way. To do it more inline with the original game would take a lot more work.

If you're still with me after all that reading, thank you. I wanted to ask you about the option you wished you had to disable returning to center. There's two approaches that could be taken, and having tested each they both feel pretty odd compared to what one expects from the original game.

1. CVAR to only disable returning to center after a fall. This means the player on a hard landing will look down and continue looking down until the player provides horizon input.
2. CVAR to disable looking down after a hard landing. This means the player lands, bobs a bit from the impact, but doesn't change where they're looking.

Easiest way to test the 2nd option is to download Raze 0.5.1 or earlier as hard landings were broken in EDuke32 at the time Graf picked things from the original source and as such, that breakage made it into Raze.

**Comment by Axldomi** [comment]
@mjr4077au Thanks for looking into this issue. I just tested the latest devbuild (29/12/2020) and I must say, it feels much better right now. It feels quite natural and I'm no longer sure whether an option to disable this behaviour is still needed. At least for me, it doesn't feel necessary anymore.

Thanks again for all your hard work in this port btw. Really appreciated it.

**Comment by mjr4077au** [comment]
Thanks for testing. So that build is at the commit I said I reverted, but good to know you like that behaviour. That is effectively the first of the two solutions I proposed, just hard-coded and not with a CVAR.

Can you please download the CI artifact from here? https://github.com/coelckers/Raze/runs/1625391027. This is a newer build (devbuild should churn out in 4 hours or so). To summarise the above, its basically like before, however you can move the mouse a bit sooner through the return to centre process.
