### ISSUE TITLE
Duke3D - 0.8.1 - Security Cameras

### ISSUE THREAD

**Issue by Axldomi** [coelckers/Raze#233]
In Raze, once you have used a certain security camera, the last screen will appear on all security cameras (even if you haven't touched them yet).

![Duke_0002](https://user-images.githubusercontent.com/71838912/101899543-48ffbd00-3bae-11eb-9b40-9030e88719fe.png)

So after using the first security camera I go to the one behind the cinema screen to find this : 

![Duke_0001](https://user-images.githubusercontent.com/71838912/101899646-6fbdf380-3bae-11eb-898e-4d1f94abf7d4.png)

While in EDuke32, I will find this :

![duke0001](https://user-images.githubusercontent.com/71838912/101899777-ab58bd80-3bae-11eb-916b-670f66f7ef69.png)

**Comment by sinisterseed** [comment]
Noticed this earlier today as well.

It seems the image gets stuck on all cameras for us, whereas in the other ports it shows correctly, indicating that the player has not interacted with them yet.

**Comment by coelckers** [comment]
It uses EDuke32's logic now. This means, only one monitor can be active at any time, and if the player gets too far away from the active monitor, it will deactivate.

The code that was there was the original, except for checks on the texture cache - because Raze no longer maintains that, but if that is what decides what to show, the entire logic cannot be replicated anymore.
