### ISSUE TITLE
[NAM] Too many sprites spawned

### ISSUE THREAD

**Issue by markanini** [coelckers/Raze#244]
Using GitHub VS release build 3ecd02dcacc8961238d980f5afa25a2088a164c4 in Windows 10. While moving through a forested area in e1l2 the error pops up: "Too many sprites spawned" I've attached the save file.
[save0000.dsave.txt](https://github.com/coelckers/Raze/files/5759081/save0000.dsave.txt)

**Comment by coelckers** [comment]
I can tell that the culprit is an excessive amount of SMALLSMOKE actors, but I have no idea how that could happen. I cannot see this in any savegame I created myself.

**Comment by markanini** [comment]
Found another spot in e2m7 that causes the error when I pass through the gate (ee5950e7ad64c00f00e10d932af36d94dbaa60f2)
[save0002.dsave.txt](https://github.com/coelckers/Raze/files/6118828/save0002.dsave.txt)

**Comment by coelckers** [comment]
From the looks of it this is a script bug triggered by a physics problem.
I could trace the second problem to some item endlessly generating explosions and that will then slowly increase the number of smoke sprites in insanely high amounts, which will eventually overflow the sprite array.. From the looks of it this is caused by an item not properly deleting itself and getting stuck in an endless loop of spawning new and ever more explosions.
I'm sorry but I have no idea how to fix this on the engine side.
