### ISSUE TITLE
Duke - beta213 - E3L2 - Weird ambient noise

### ISSUE THREAD

**Issue by Axldomi** [coelckers/Raze#288]
In E3L2 "Bank Roll", I'm experiencing some weird ambient noises at the place below (I also provided a savegame).

![Duke_0009](https://user-images.githubusercontent.com/71838912/112731178-06cc7280-8f36-11eb-956e-20bf7541bc81.png)

[save0000.zip](https://github.com/coelckers/Raze/files/6216214/save0000.zip)

This does not happen in the other ports.

**Comment by sinisterseed** [comment]
I wonder if it isn't the reverb weirdness again.

**Comment by coelckers** [comment]
No, it's not reverb, it's a looped sound that isn't stopped.

**Comment by coelckers** [comment]
Classic Duke shittiness. We got a sound controller playing a sound on another sprite that gets removed between starting and stopping the sound. The entire setup relies on undefined side effects that Raze's sound engine can not replicate so instead of stopping the sound it gets restarted. And since the sound loops it never stops.
