### ISSUE TITLE
[scriptable_cutscenes] [Duke, RR & Blood] Warping to a map causes the cutscene from the current episode to play before transitioning

### ISSUE THREAD

**Issue by sinisterseed** [coelckers/Raze#339]
For instance, start episode 3, then warp to E1L5.

When you do, episode 3's end game will play before the end level screen and finally transitioning to the new level.

**Comment by sinisterseed** [comment]
Actually, the exact same behavior is found it Blood as well.

**Comment by sinisterseed** [comment]
Double correction, same thing in RR.

**Comment by coelckers** [comment]
You'll find this in all games. If you change map clusters while continuing the game the game will play the exact cutscenes that would get played if you transitioned naturally between these two levels.
It's the same when you try that in GZDoom: It will also trigger the intermissions that would get played if doing that.

Right now I need this behavior for testing so it'll stay in. 
But this is not easy to change because 'changemap' and 'levelwarp' just simulate normal game behavior of initiating a map transition.

**Comment by arrowgent** [comment]
levelwarp?

i just use "map e1m1" to start a map
is levelwarp a build feature or a gzdoom feature?

agreed on the cutscenes are part of the map definition
seems like a feature more than a bug?  there would be times id prefer the cutscene to play
