### ISSUE TITLE
[newrender] [Duke] Finishing E4L9 Derelicts plays E4's end game before the intermission

### ISSUE THREAD

**Issue by sinisterseed** [coelckers/Raze#350]
Basically the title.

**Comment by coelckers** [comment]
How did you start the map?
Duke's secret map exits only work if you regularly visit the map by exiting the one with the secret exit. The maps need to get their destination set by that previous map. If you start it from the console, the game has no clue where to go at the end and just takes the regular progression to the next map - and since that does not exist, it ends the game.

**Comment by coelckers** [comment]
I was unable to reproduce this. It properly recognized that there's no cutscenes registered for this transition.
If you get this again, please give a detailed description of what you did - as it stands I can see no bug here.

**Comment by sinisterseed** [comment]
This works now as well.

Alright, I have no idea what happened last night. Also checked some other maps such as E3L9, no problem. Maybe the CI I used was before one of the crucial fixes, so I ended up with lots of breakage.

**Comment by coelckers** [comment]
That's likely. I did a complete export of the internal data yesterday and found a few issues causing progression breakage, like incorrect level numbers being assigned, etc. This may well have been caused by that.
