### ISSUE TITLE
[Blood] Seams in some skyboxes.

### ISSUE THREAD

**Issue by valter12437** [coelckers/Raze#381]
The skyboxes of some levels like E2M3, E3M2, E4M1, CP02 and E6M1 still have seams in them.

E2M3
![Blood_0000](https://user-images.githubusercontent.com/82282361/118407938-7408a400-b659-11eb-81e3-d8baaa3a9939.png)

E3M2
![Blood_0003](https://user-images.githubusercontent.com/82282361/118407805-bd0c2880-b658-11eb-8e88-2cb3c61a8c3a.png)

E4M1
![Blood_0004](https://user-images.githubusercontent.com/82282361/118407949-897dce00-b659-11eb-9203-c34c37eac1f5.png)

CP02
![Blood_0008](https://user-images.githubusercontent.com/82282361/118407875-24c27380-b659-11eb-8cf0-2d494e6827f2.png)

E6M1
![Blood_0007](https://user-images.githubusercontent.com/82282361/118407922-589d9900-b659-11eb-8d2c-09c2dbbec406.png)

**Comment by coelckers** [comment]
Known issue with the sky renderer. With the new renderer this will no longer be an issue, and the one for Polymost cannot really be fixed.

**Comment by sinisterseed** [comment]
Those are also not seams. I guess you're referring to the line where the sky looks like it splits.

That's just how Polymost sky rendering works, it uses parts of the skybox to cover the otherwise empty top, which is how Build skies rendered originally. SW is the only game where this doesn't occur, as its sky textures just get shifted weirdly with the player's view.

**Comment by coelckers** [comment]
This happens if skies do not wrap and get a negative offset in the map.
It's just atrociously poor design in the engine. The sky implementation is one major catastrophe and some games really have abused this to hell and back. In Nam one sky is shifted up half its entire height because the horizon was drawn too low.
