### ISSUE TITLE
[Duke WT] Mini bosses instead of the actual boss monsters on some levels

### ISSUE THREAD

**Issue by sinisterseed** [coelckers/Raze#409]
So in light of Civvie's recent review of WT (played through Raze x3), it would seem there are a few omissions compared to Gearbox's port - https://www.youtube.com/watch?v=soYqDq9nGIg

Most glaring one is the absence of boss monsters on some maps. First one is on Prima Arena, the Battlelord just outside the map is supposed to be just that, but we have a mini Battlelord instead.

Same goes for Tour de Nukem. There's a mini Battlelord guarding the exit instead of the big version.

And same once more for Red Ruckus, one of the monsters is supposed to be the big version but instead all of them are mini variants (8:49 in the video).

**Comment by coelckers** [comment]
Yuck, this is nasty. Looking at EDuke32's code, WT made a change to how boss spawning works that is incompatible with regular Duke.

This means we cannot run the WT config with stock maps as this would make mini-Battlelords spawn as the full version.

Will have to check how to properly handle this so that this won't break stuff. I can confirm that fixing this for WT will definitely break E4L9 for regular Duke when playing with Nightfright's generated episode.

**Comment by coelckers** [comment]
Fixed in db21313c96c28d1cff5cec3164624ca717168279
Utterly gross, but well...
