### ISSUE TITLE
(Blood) Crosshair placement

### ISSUE THREAD

**Issue by Tchernobog1** [coelckers/Raze#421]
I noticed that in DOSBox, the crosshair placement was located above the center of the screen. In NBlood, if I remember correctly, there was an option called "center horizontal line", where having it off puts the crosshair above the center of the screen like in DOSBox, and on puts it in the center, which is similar to how the other Build engine games do it.
Here comes my question. Is it possible to add this feature in Raze for Blood?

**Comment by mjr4077au** [comment]
I was the one that removed this when redoing the input code as it was easier to handle all the games on a centre horizon of 0 vs. 100 for Duke/SW, 92 for Exhumed and 90 for Blood. It would have also assisted in the development of the new renderer as well.

It's more than just the position of the crosshair, it involved the pitch of the player as well.

I'll leave this open for Graf to chime in on as to whether he wants it bought back in some way, shape or form. At the time, the thought was around standardisation for a consistent feel between the games.

**Comment by mjr4077au** [comment]
Realistically I don't think this will ever be re-introduced. As said, it's more than the crosshair being positioned above the centre line, but rather the player's projection was adjusted as well to match the y-shearing of the software renderer. I removed that when I was redoing the horizon code to make it easier when it came time to start setting up the new renderer.

Because this was so dependent on how Polymost projected itself onto the screen, I can't see what we can do about this.

**Comment by coelckers** [comment]
We can surely add a crosshair offset, but I have my doubts that everybody would want this as the only setting, so it'd have to be a user option.

Regarding the projection hackery, no that I do not want to have back.

**Comment by mjr4077au** [comment]
If we add the offset, we had to adjust the aiming code to get it to shoot higher as well, this is stored as `pPlayer->slope` which is the player's horizon in Q16 shifted right by 9. Maybe after we make further progress with converting projectiles to pitch math?
