### ISSUE TITLE
An android port eventually 

### ISSUE THREAD

**Issue by gumziler** [coelckers/Raze#446]
We can't play blood, SW and DN3D etc really good on android and this one source port is capable of playing every build engine game on a GZDOOM based engine and it is possible to port it because you can play GZDOOM on android what means you could port it if you want I would kill for it.

**Comment by coelckers** [comment]
This would have to be a separate project, so opening a ticket here is not going to help

**Comment by Gaerzi** [comment]
Beloko [is working on a "Raze Touch" port](https://www.doomworld.com/forum/topic/106799-delta-touch-on-android/?page=11&tab=comments#comment-2321004). It may not be distributed on Google Play, though, for legal reasons -- the Build license not allowing commercial use. So watch out [the official website](http://opentouchgaming.com/raze-touch/) for if and when it eventually gets actual content in it, instead of an empty rubric.
