### ISSUE TITLE
[Duke3D] WT Mini-Hud not displaying correctly in Raze

### ISSUE THREAD

**Issue by doon343** [coelckers/Raze#447]
Is there any way to fix this? The mini hud in Raze does not have the armor box, and is not aligned to the right, even though I am using WT.
 
![20210626193447_1](https://user-images.githubusercontent.com/86077898/123529542-e1770e00-d6b6-11eb-9ca0-11c49191a86d.jpg)
![20210626193308_1](https://user-images.githubusercontent.com/86077898/123529544-e50a9500-d6b6-11eb-959a-84abe33e2dc2.jpg)

**Comment by coelckers** [comment]
The armor box was not present in the original DOS version, which is what gets replicated here.

The alignment is to the bottom left corner and not to the bottom left of the 4:3 center part of the screen - this part is fully intentional and won't be changed. Looks like WT has no good widescreen support in place here which I'd consider broken.

**Comment by sinisterseed** [comment]
Same here. Looking at what WT *isn't* doing reveals that the HUD does not actually adapt to the resolution, especially in widescreen video formats.

Thjs was present in Fresh Supply as well for the mini HUD, not sure if it was ever fixed for that game. Either way, what we're doing here is on purpose and thus, it will stay as it is.

**Comment by Gaerzi** [comment]
There's something to be said about UI positioning from the center of the screen, rather than for the edge, because usually the attention is focused on the center and with ultrawide it can be cumbersome to have to move the eye all the way to the side to look at important info. Though it's more of an issue with split HUDs where info is scattered to several corners.

**Comment by sinisterseed** [comment]
That's actually a fair point. For ultrawide, having the split HUD elements centered like this could be useful since these screens are so, well, wide.

Hm, yes, perhaps this should be considered indeed, especially since ultrawide is becoming more popular these days.
