### ISSUE TITLE
Shadow Warrior: Wanton Destruction (WT) expansion crashes on exit

### ISSUE THREAD

**Issue by Tasosgemah** [coelckers/Raze#464]
I have an issue with this expansion
When i exit Wanton Destruction (WT) the client crashes

Code: C0000005 (Access Violation - tried to read address 000001D66F35488C)
Address: 00007FF67D9D1910
Flags: 00000000

It does load and seems to play well otherwise. I tried a bunch of different files, they all seem to crash on exit.

**Comment by coelckers** [comment]
Please post the entire crash log. This does not give us any info.

**Comment by Tasosgemah** [comment]
https://pastebin.com/kvj8sF8D

**Comment by sinisterseed** [comment]
Same here, I got WD crashing on my end as well recently on exit.

**Comment by mjr4077au** [comment]
Were either of you doing anything specific so I can recreate this? I can't get it to crash from my end, but don't know if I need to play through some or all of a level, etc.

**Comment by sinisterseed** [comment]
I'll see if I can get a crash again, I didn't add any logs last time since OP already did it, but I just compiled, did my settings, started the first map, then quit. Crashed.

**Comment by Tasosgemah** [comment]
I didn't have to do anything. Just starting the game and then quitting makes it crash.

**Comment by mjr4077au** [comment]
Still can't replicate it here...

@sinisterseed can you try with a RelWithDebInfo build and see if it crashes for you there? After it's built, do the following:

1. Start raze.exe
2. In MSVC, click Debug > Attach to Process:
![image](https://user-images.githubusercontent.com/48643140/125180897-c1ad2180-e242-11eb-9b60-ee5921e48ff4.png)
3. Find raze.exe in the list of processes and press "Attach":
![image](https://user-images.githubusercontent.com/48643140/125180909-ee613900-e242-11eb-8519-014ba44ed17f.png)
4. When the debugger has completed loading, play Raze as per normal and try to make it crash. MSVC should show you in the code where the break occurred.

Need to do this because I can't seem to open the mdump file against my build.

**Comment by alexey-lysiuk** [comment]
You don't need to do these steps in order to start debugging from Visual Studio. Instead, set Command to a path to Raze executable at Debugging page of **ALL_BUILD** project properties. This needs to be done once per configuration.
To avoid mistakes, path to executable can be copied from the same page of **raze** project. It is displayed as `$(TargetPath)`, but a dialog will show full path if you click on `<Edit>` in Command combo box.

**Comment by alexey-lysiuk** [comment]
Callstack of this crash
```
 	FGameTexture::GetDisplayHeight() Line 128	C++
>	tileHeight(int num) Line 423	C++
 	ShadowWarrior::SPRITEp_SIZE_Z(const spritetype * sp) Line 299	C++
 	ShadowWarrior::SPRITEp_SIZE_TOS(const spritetype * sp) Line 313	C++
 	ShadowWarrior::DoActorPickClosePlayer(short SpriteNum) Line 400	C++
 	ShadowWarrior::KillSprite(short SpriteNum) Line 774	C++
 	ShadowWarrior::TerminateLevel() Line 459	C++
 	ShadowWarrior::GameInterface::FreeGameData() Line 749	C++
 	GameMain() Line 589	C++
 	DoMain(HINSTANCE__ * hInstance) Line 971	C++
```
`TileFiles.tiledata` seems to be freed already when the given code is called.

**Comment by Tasosgemah** [comment]
Seeing how the expansion is freeware, could we exchange the files we are using for testing?

**Comment by mjr4077au** [comment]
> Callstack of this crash
> 
> ```
>  	FGameTexture::GetDisplayHeight() Line 128	C++
> >	tileHeight(int num) Line 423	C++
>  	ShadowWarrior::SPRITEp_SIZE_Z(const spritetype * sp) Line 299	C++
>  	ShadowWarrior::SPRITEp_SIZE_TOS(const spritetype * sp) Line 313	C++
>  	ShadowWarrior::DoActorPickClosePlayer(short SpriteNum) Line 400	C++
>  	ShadowWarrior::KillSprite(short SpriteNum) Line 774	C++
>  	ShadowWarrior::TerminateLevel() Line 459	C++
>  	ShadowWarrior::GameInterface::FreeGameData() Line 749	C++
>  	GameMain() Line 589	C++
>  	DoMain(HINSTANCE__ * hInstance) Line 971	C++
> ```
> 
> `TileFiles.tiledata` seems to be freed already when the given code is called.

@alexey-lysiuk do you mind if I ask how you open the minidump file to get usuable data out of it? I can't get it to work in MSVC properly...

**Comment by alexey-lysiuk** [comment]
Callstack wasn’t from minidump. It was a locally built version that ran under Visual Studio debugger.

**Comment by mjr4077au** [comment]
Ah ok thanks for that. Are the minidumps of any real use or not really?

**Comment by alexey-lysiuk** [comment]
Minidumps are usable if you have an executable that produced it, and the corresponding .pdb file. Without the latter, things are getting more complicated, but it’s still possible to gather some information. It’s almost useless without executable because minidump contains very little data by itself.
