### ISSUE TITLE
[Blood] 'No volumes defined' error with voxel pack

### ISSUE THREAD

**Issue by Unikat2000** [coelckers/Raze#469]
When using the latest Blood Voxel Pack  https://github.com/fgsfds/Blood-Voxel-Pack and Raze 1.1.2.  the engine crashes with an error while starting up OUWB. Cryptic Passage with the same Pack is working fine. The maintainer @Dzierzan was unable to reproduce this issue.

![Screenshot 2021-07-11 125237](https://user-images.githubusercontent.com/16125110/125192211-e905ed80-e246-11eb-8c6f-871ac62f5fbc.png)

**Comment by mjr4077au** [comment]
It's because of `MODELS.INI` that's trying to load.

@Dzierzan, is the presence of this file necessary in the voxel pack? With our autoload process, it's trying to parse the file for level information.

**Comment by Dzierzan** [comment]
Will moving this file to let's say XMAPEDIT folder fix that? As the name suggests, it's for XMAPEDIT, as @NoOneBlood wrote support for that (not released yet).

**Comment by mjr4077au** [comment]
Unfortunately not since we scan subfolders for .INI files so we can load things like Death Wish where content is in a folder within the ZIP file.

@coelckers, could we perhaps extend bfcedc2177ccb1b65d27d40f49adab18414f3b85 to parse the .INI file for legitimacy before declaring we found one? Perhaps if the INI file doesn't include an `[Episode#]` header, it gets bypassed?

**Comment by Dzierzan** [comment]
Alright

@Unikat2000 remove `MODELS.INI` for now. You don't need it anyway.

**Comment by Unikat2000** [comment]
ok thx for the fast solution :)

**Comment by coelckers** [comment]
fixed in 6576adb80b91d9bad93a7d1ac27a25685590fdf4
