### ISSUE TITLE
multiplayer 

### ISSUE THREAD

**Issue by art7799372** [coelckers/Raze#576]
### Raze version

1.2.1

### Which game are you running with Raze?

Duke Nukem 3D

### What Operating System are you using?

Windows 11

### Is your feature request related to a problem? Please describe.

no

### Describe the solution you'd like

no

### Describe alternatives you've considered

I am trying to do multiplayer on the RAZE engine would you like to help me? I have already made the menu with join lobby and create lobby and all the options the server and many other things ...

**Comment by art7799372** [comment]
there i need help spawning on deathmatch and coop parts, i'm looking for codes that could help me implement spawns. thank you

**Comment by coelckers** [comment]
Raze currently does not support multiplayer. Due to lack of manpower this is unlikely to change for the foreseeable future.

**Comment by art7799372** [comment]
i am doing it

**Comment by art7799372** [comment]
https://user-images.githubusercontent.com/73469015/140429842-6e5e577f-628d-443b-8c18-e5d4bb35c76f.mp4

**Comment by mjr4077au** [comment]
>  multi.mp4

It's great to see someone taking an interest in the MP code since I think it would increase our audience. Have you done any work on the underlying networking code or just the UI stuff?

The main loop is GZDoom's and is fully prepared for networking, however nothing from the game side is hooked up. The prediction code from each game would also likely need significant work as well.

**Comment by art7799372** [comment]
I continue to work... its ok... no problem
