### ISSUE TITLE
[gb57e13ff6] [General] Weapons continue firing after closing and opening the menu

### ISSUE THREAD

**Issue by sinisterseed** [coelckers/Raze#95]
Found this while screwing around in Duke, it seems opening and closing the menu when firing a weapon causes it to keep firing afterwards, like some sort of residual input.

To reproduce: Load up a game (Duke in this case), hold down fire on a weapon - I find the pistol the most convenient for the purpose - then open the menu. Now lift your hand off the mouse and start spamming Escape. Eventually the pistol will start firing despite not receiving any more direct input from the mouse.

**Comment by coelckers** [comment]
Nothing wrong here - it sometimes happens that the game action has already been triggered before the menu opens but then the game gets paused and the weapon fires after closing the menu.

It is very deliberate that the menu lives completely outside the game, it has no influence on what the game does so that after unpausing everything goes on as previously determined.
